import subprocess
import threading
import os
import sys
import shutil

class Builder:
    def __init__(self, log_callback, done_callback):
        self.log_callback = log_callback
        self.done_callback = done_callback
        self.process = None

    def build_pyinstaller(self, config):
        cmd = ["pyinstaller", "-y"]
        
        if config.get("onefile"):
            cmd.append("--onefile")
        if config.get("noconsole"):
            cmd.append("--noconsole")
        
        icon_path = config.get("icon")
        if icon_path and os.path.exists(icon_path):
            cmd.extend(["--icon", icon_path])
            
        app_name = config.get("app_name")
        if app_name:
            cmd.extend(["--name", app_name])
            
        output_dir = config.get("output_dir")
        if output_dir:
            cmd.extend(["--distpath", output_dir])
            
        main_script = config.get("main_script")
        if not main_script or not os.path.exists(main_script):
            self.log_callback("Error: Chưa chọn file main.py hoặc file không tồn tại\n")
            self.done_callback(False)
            return

        data_items = config.get("data_items", [])
        extract_items = []
        
        for item in data_items:
            path = item.get("path")
            if path and os.path.exists(path):
                # Add to pyinstaller
                # Windows format: src;dest
                basename = os.path.basename(path)
                cmd.extend(["--add-data", f"{path};{basename}"])
                
                if item.get("mode") == "Giải nén":
                    extract_items.append(basename)

        # Handle wrapper generation if there are extract items
        build_script = main_script
        wrapper_path = None
        
        if extract_items:
            self.log_callback(f"Đang tạo wrapper để giải nén {len(extract_items)} file/thư mục...\n")
            main_dir = os.path.dirname(main_script)
            wrapper_path = os.path.join(main_dir, "pypackgui_wrapper.py")
            
            try:
                with open(main_script, 'r', encoding='utf-8') as f:
                    original_code = f.read()
                    
                wrapper_code = f'''
# ==========================================
# AUTO-GENERATED BY PYPACKGUI
# This wrapper extracts editable data files
# ==========================================
import sys
import os
import shutil

def _pypackgui_extract_editable_data():
    if not hasattr(sys, '_MEIPASS'):
        return

    base_path = sys._MEIPASS
    exe_dir = os.path.dirname(sys.executable)
    
    extract_items = {extract_items}
    
    for item in extract_items:
        src = os.path.join(base_path, item)
        dst = os.path.join(exe_dir, item)
        
        try:
            if os.path.isdir(src):
                if os.path.exists(dst):
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)
            elif os.path.isfile(src):
                if os.path.exists(dst):
                    os.remove(dst)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copy2(src, dst)
        except Exception as e:
            print(f"PyPackGUI Extract Error: {{e}}")

_pypackgui_extract_editable_data()
# ==========================================
# ORIGINAL SCRIPT BEGINS HERE
# ==========================================
''' + original_code
                
                with open(wrapper_path, 'w', encoding='utf-8') as f:
                    f.write(wrapper_code)
                    
                build_script = wrapper_path
            except Exception as e:
                self.log_callback(f"Lỗi khi tạo wrapper: {e}\n")
                self.done_callback(False)
                return

        cmd.append(build_script)
        
        self.log_callback(f"Running command: {' '.join(cmd)}\n")
        
        def run_cmd():
            try:
                cmd_run = ["python", "-m", "PyInstaller"] + cmd[1:]
                self.process = subprocess.Popen(cmd_run, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1, universal_newlines=True, creationflags=subprocess.CREATE_NO_WINDOW)
                for line in self.process.stdout:
                    self.log_callback(line)
                self.process.wait()
                
                # Cleanup wrapper if exists
                if wrapper_path and os.path.exists(wrapper_path):
                    try:
                        os.remove(wrapper_path)
                    except:
                        pass
                        
                if self.process.returncode == 0:
                    self.log_callback("\n[BUILD SUCCESS]\n")
                    self.done_callback(True)
                else:
                    self.log_callback(f"\n[BUILD FAILED] with code {self.process.returncode}\n")
                    self.done_callback(False)
            except Exception as e:
                self.log_callback(f"\n[ERROR] {str(e)}\n")
                self.done_callback(False)

        threading.Thread(target=run_cmd, daemon=True).start()
