#Direct ResourceBundle
#Mon Oct 17 14:50:46 ICT 2016
HTML_HEAD_O = <html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"vi\" lang=\"vi\"><head>
HTML_HEAD_C = </title><style>*{margin:0!important;}body{margin:8px!important;}a{font-weight:700;text-decoration:none}a.toclv2{color:red;text-align:center}h2{color:red;font-weight:700}.chapter-img{font-weight:100}#info{font-weight:700;text-align:center;}#nt,#tg{color:red;}#cvt{color:blue;}#ng{color:purple;}#gt{font-weight:100}#sc{color:green}#tt{color:blue}</style></head><body><a name=\"toc\"></a>
HTML_C = </body></html>
HTML_ANCHOR_O = <a href=\"#
HTML_ANCHOR_C = </a><br/>
HTML_ID_O = <br><br><h2 id=\"
HTML_ID_C = </h2><br><br><br>
HTML_EBOOK_O = <div id="info"><p id=\"-1\">Thông Tin Ebook</p>
HTML_EBOOK_CREATOR_O = <p id="nt">Ng\u01B0\u1EDDi t\u1EA1o: 
HTML_EBOOK_P_C = </p>
HTML_EBOOK_CONVERTER_O = <p id="cvt">Converter: 
HTML_EBOOK_SOURCE_O = <p id="ng">Ngu\u1ED3n: 
HTML_EBOOK_INTRO_O = <p>Gi\u1EDBi thi\u1EC7u</p><p id="gt">
HTML_EBOOK_STORY_O = <p id="tt">Truy\u1EC7n: 
HTML_EBOOK_AUTHOR_O = <p id="tg">Tác Gi\u1EA3: 
HTML_EBOOK_STATUS_O = <p id="sc">Tình Tr\u1EA1ng: 
HTML_EBOOK_C = </div>
JS_COPY_COOKIES=(function(){var e=document.createElement('textarea');var p=document.createElement('p');e.style.width="100%";e.style.height="200px";p.style.fontWeight="900";p.style.fontSize="24px";p.innerHTML='Chép n\u1ED9i dung \u1EDF textbox d\u01B0\u1EDBi vào GetManual(CTRL + A, CTRL + C)';var fl=function(s){console.clear();console.info("Sao chép "+(s?"thành công":"th\u1EA5t b\u1EA1i"));if(s){console.info('Quay l\u1EA1i \u0110\u0103ng Nh\u1EADp nhanh -> Dán & L\u01B0u Thông Tin \u0110\u0103ng Nh\u1EADp')} if(!s){console.info("T\u1EF1 \u0111\u1ED9ng sao chép vào Clipboard không thành công, b\u1EA1n c\u1EA7n t\u1EF1 chép t\u1EEB textbox vào ph\u1EA7n m\u1EC1m.");}};e.value=`${window.location.host}@###@${document.cookie}`;document.body.appendChild(p);document.body.appendChild(e);e.select();e.focus();var s=document.execCommand("copy");window.scroll(0,99999);fl(s);})();
CONFIG_TRUYENDICH_ORG_API_HOST=http://5.189.141.169:8080